### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by bronnel** [stumi01/iTunesSample#1]
Hi can you help how to add the api keys for develop branch of Mizuu
please help.

**Comment by stumi01** [comment]
https://github.com/MizzleDK/Mizuu/blob/master/CONTRIBUTING.md

**Comment by bronnel** [comment]
@stumi01 ok thanks I know that, but this is for master branch, you have a fork for the develop branch which may have the fixes I need, the keys has to be in keys.gradle file please can you help?

**Comment by bronnel** [comment]
@stumi01 I want to talk to you, I sent invitation for your google hangout can you accept?
